# SPDX-FileCopyrightText: © 2026 Antti Kivi <antti@anttikivi.com>
# SPDX-License-Identifier: Apache-2.0

name: ci

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.event.pull_request.number || forgejo.ref }}
  cancel-in-progress: ${{ forgejo.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  reuse:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6.0.2
      - run: apt update
      - run: apt install -y reuse
      - run: reuse lint
  test:
    runs-on: codeberg-tiny
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6.0.2
      - uses: https://codeberg.org/mlugg/setup-zig@v2.2.1
      - run: zig build test-unit --summary all
