#!/bin/sh

set -eu

ZIG_VERSION="0.15.2"
ZIG_PUBLIC_KEY="RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"
ZIG_MIRRORS_URL="https://ziglang.org/download/community-mirrors.txt"
# The list of mirrors as of 2026-02-21 as a backup if ziglang.org is unavailable
ZIG_FALLBACK_MIRRORS="$(
    cat <<EOF
https://pkg.machengine.org/zig
https://zigmirror.hryx.net/zig
https://zig.linus.dev/zig
https://zig.squirl.dev
https://zig.florent.dev
https://zig.mirror.mschae23.de/zig
https://zigmirror.meox.dev
https://ziglang.freetls.fastly.net
https://zig.tilok.dev
https://zig-mirror.tsimnet.eu/zig
https://zig.karearl.com/zig
https://pkg.earth/zig
https://fs.liujiacai.net/zigbuilds
EOF
)"
ZIG_MIRROR_LIST="$(curl -fsSL "${ZIG_MIRRORS_URL}" 2>/dev/null || echo "${ZIG_FALLBACK_MIRRORS}")"
ZIG_MIRROR="$(echo "${ZIG_MIRROR_LIST}" | grep . | sort -R | head -n 1)"

echo "downloading Zig ${ZIG_VERSION} from ${ZIG_MIRROR}..."

if [ "$(uname -m)" = "arm64" ] || [ "$(uname -m)" = "aarch64" ]; then
    ZIG_ARCH="aarch64"
else
    ZIG_ARCH="x86_64"
fi

case "$(uname)" in
Darwin)
    ZIG_OS="macos"
    ZIG_EXTENSION=".tar.xz"
    ;;
FreeBSD)
    ZIG_OS="freebsd"
    ZIG_EXTENSION=".tar.xz"
    ;;
Linux)
    ZIG_OS="linux"
    ZIG_EXTENSION=".tar.xz"
    ;;
*)
    echo "unsupported operating system: $(uname)" >&2
    exit 1
    ;;
esac

ZIG_ARCHIVE="zig-${ZIG_ARCH}-${ZIG_OS}-${ZIG_VERSION}${ZIG_EXTENSION}"
ZIG_DIRECTORY="$(basename "${ZIG_ARCHIVE}" "${ZIG_EXTENSION}")"
ZIG_URL="${ZIG_MIRROR}/${ZIG_ARCHIVE}?source=anttikivi%2Ftoml-zig"
ZIG_SIGNATURE_URL="${ZIG_MIRROR}/${ZIG_ARCHIVE}.minisig?source=anttikivi%2Ftoml-zig"

# Install minisign if it is missing. We should not download anything before we
# know that we can verify it.
if ! command -v minisign >/dev/null 2>&1; then
    echo "installing minisign..."

    case "$(uname)" in
    Darwin)
        if command -v brew >/dev/null 2>&1; then
            brew install minisign
        else
            echo "Homebrew not found" >&2
            exit 1
        fi
        ;;
    FreeBSD)
        if command -v pkg >/dev/null 2>&1; then
            pkg install -y minisign
        else
            echo "pkg not found" >&2
            exit 1
        fi
        ;;
    Linux)
        if command -v apt-get >/dev/null 2>&1; then
            apt-get update -y
            apt-get install -y minisign
        elif command -v dnf >/dev/null 2>&1; then
            dnf install -y minisign
        elif command -v yum >/dev/null 2>&1; then
            yum install -y minisign
        elif command -v pacman >/dev/null 2>&1; then
            pacman -Sy --noconfirm minisign
        elif command -v zypper >/dev/null 2>&1; then
            zypper --non-interactive install minisign
        elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache minisign
        else
            echo "unable to install minisign" >&2
            exit 1
        fi
        ;;
    NetBSD)
        if command -v pkgin >/dev/null 2>&1; then
            pkgin -y install minisign
        elif command -v pkg_add >/dev/null 2>&1; then
            pkg_add minisign
        else
            echo "neither pkgin nor pkg_add found" >&2
            exit 1
        fi
        ;;
    *)
        echo "unsupported operating system: $(uname)" >&2
        exit 1
        ;;
    esac

    command -v minisign >/dev/null 2>&1
fi

echo "downloading archive from ${ZIG_URL}..."

if command -v curl >/dev/null 2>&1; then
    curl -fsSLo "${ZIG_ARCHIVE}" "${ZIG_URL}"
    curl -fsSLo "${ZIG_ARCHIVE}.minisig" "${ZIG_SIGNATURE_URL}"
elif command -v wget >/dev/null 2>&1; then
    wget -4qO "${ZIG_ARCHIVE}" "${ZIG_URL}"
    wget -4qO "${ZIG_ARCHIVE}.minisig" "${ZIG_SIGNATURE_URL}"
else
    echo "neither curl nor wget available" >&2
    exit 1
fi

echo "verifying ${ZIG_ARCHIVE}..."
minisign -Vm "${ZIG_ARCHIVE}" -x "${ZIG_ARCHIVE}.minisig" -P "${ZIG_PUBLIC_KEY}"
rm -f "${ZIG_ARCHIVE}.minisig"

echo "extracting ${ZIG_ARCHIVE}..."
case "${ZIG_EXTENSION}" in
".tar.xz")
    tar -xf "${ZIG_ARCHIVE}"
    ;;
*)
    echo "Zig archive format '${ZIG_EXTENSION}' not supported" >&2
    exit 1
    ;;
esac
rm "${ZIG_ARCHIVE}"

mkdir zig

rm -rf zig/doc
rm -rf zig/lib
mv "${ZIG_DIRECTORY}/LICENSE" zig/
mv "${ZIG_DIRECTORY}/README.md" zig/
mv "${ZIG_DIRECTORY}/doc" zig/
mv "${ZIG_DIRECTORY}/lib" zig/
mv "${ZIG_DIRECTORY}/zig" zig/

rmdir "${ZIG_DIRECTORY}"

ZIG_BIN="$(pwd)/zig/zig"
echo "Zig ${ZIG_VERSION} available at ${ZIG_BIN}"
