#!/bin/sh

set -eu

[ $# -ge 2 ] || {
    echo "usage: download_zig <version> <destdir>" >&2
    exit 1
}

if [ -z "$1" ]; then
    echo "no Zig version argument passed to 'download_zig'" >&2
    exit 1
fi

if [ -z "$2" ]; then
    echo "no destination directory argument passed to 'download_zig'" >&2
    exit 1
fi

ZIG_VERSION="$1"
ZIG_DESTINATION_DIR="$2"

ZIG_PUBLIC_KEY="RWSGOq2NVecA2UPNdBUZykf1CCb147pkmdtYxgb3Ti+JO/wCYvhbAb/U"
ZIG_MIRRORS_URL="https://ziglang.org/download/community-mirrors.txt"
# The list of mirrors as of 2026-02-21 as a backup if ziglang.org is unavailable
ZIG_FALLBACK_MIRRORS="$(
    cat <<EOF
https://pkg.machengine.org/zig
https://zigmirror.hryx.net/zig
https://zig.linus.dev/zig
https://zig.squirl.dev
https://zig.florent.dev
https://zig.mirror.mschae23.de/zig
https://zigmirror.meox.dev
https://ziglang.freetls.fastly.net
https://zig.tilok.dev
https://zig-mirror.tsimnet.eu/zig
https://zig.karearl.com/zig
https://pkg.earth/zig
https://fs.liujiacai.net/zigbuilds
EOF
)"
ZIG_MIRROR_LIST="$(curl -fsSL "${ZIG_MIRRORS_URL}" 2>/dev/null || echo "${ZIG_FALLBACK_MIRRORS}")"
ZIG_MIRROR="$(echo "${ZIG_MIRROR_LIST}" | grep . | sort -R | head -n 1)"

echo "downloading Zig ${ZIG_VERSION} from ${ZIG_MIRROR}..."

if [ "$(uname -m)" = "arm64" ] || [ "$(uname -m)" = "aarch64" ]; then
    ZIG_ARCH="aarch64"
else
    ZIG_ARCH="x86_64"
fi

case "$(uname)" in
Darwin)
    ZIG_OS="macos"
    ZIG_EXTENSION=".tar.xz"
    ;;
FreeBSD)
    ZIG_OS="freebsd"
    ZIG_EXTENSION=".tar.xz"
    ;;
Linux)
    ZIG_OS="linux"
    ZIG_EXTENSION=".tar.xz"
    ;;
*)
    echo "unsupported operating system: $(uname)" >&2
    exit 1
    ;;
esac

ZIG_ARCHIVE="zig-${ZIG_ARCH}-${ZIG_OS}-${ZIG_VERSION}${ZIG_EXTENSION}"
ZIG_DIRECTORY="$(basename "${ZIG_ARCHIVE}" "${ZIG_EXTENSION}")"
ZIG_URL="${ZIG_MIRROR}/${ZIG_ARCHIVE}?source=anttikivi%2Ftoml-zig"
ZIG_SIGNATURE_URL="${ZIG_MIRROR}/${ZIG_ARCHIVE}.minisig?source=anttikivi%2Ftoml-zig"

# Install minisign if it is missing. We should not download anything before we
# know that we can verify it.
if ! command -v minisign >/dev/null 2>&1; then
    exit 1
fi

echo "downloading archive from ${ZIG_URL}..."

if command -v curl >/dev/null 2>&1; then
    curl -fsSLo "${ZIG_ARCHIVE}" "${ZIG_URL}"
    curl -fsSLo "${ZIG_ARCHIVE}.minisig" "${ZIG_SIGNATURE_URL}"
elif command -v wget >/dev/null 2>&1; then
    wget -4qO "${ZIG_ARCHIVE}" "${ZIG_URL}"
    wget -4qO "${ZIG_ARCHIVE}.minisig" "${ZIG_SIGNATURE_URL}"
else
    echo "neither curl nor wget available" >&2
    exit 1
fi

echo "verifying ${ZIG_ARCHIVE}..."
minisign -Vm "${ZIG_ARCHIVE}" -x "${ZIG_ARCHIVE}.minisig" -P "${ZIG_PUBLIC_KEY}"
rm -f "${ZIG_ARCHIVE}.minisig"

echo "extracting ${ZIG_ARCHIVE}..."
case "${ZIG_EXTENSION}" in
".tar.xz")
    tar -xf "${ZIG_ARCHIVE}"
    ;;
*)
    echo "Zig archive format '${ZIG_EXTENSION}' not supported" >&2
    exit 1
    ;;
esac
rm "${ZIG_ARCHIVE}"

rm -rf "${ZIG_DESTINATION_DIR:?}"
mkdir -p "${ZIG_DESTINATION_DIR:?}"

mv "${ZIG_DIRECTORY}/LICENSE" "${ZIG_DESTINATION_DIR}/"
mv "${ZIG_DIRECTORY}/README.md" "${ZIG_DESTINATION_DIR}/"
mv "${ZIG_DIRECTORY}/doc" "${ZIG_DESTINATION_DIR}/"
mv "${ZIG_DIRECTORY}/lib" "${ZIG_DESTINATION_DIR}/"
mv "${ZIG_DIRECTORY}/zig" "${ZIG_DESTINATION_DIR}/"

rmdir "${ZIG_DIRECTORY}"

ZIG_BIN="${ZIG_DESTINATION_DIR}/zig"
echo "Zig ${ZIG_VERSION} available at ${ZIG_BIN}"
