# SPDX-FileCopyrightText: © 2026 Antti Kivi <antti@anttikivi.com>
# SPDX-License-Identifier: Apache-2.0

name: bench

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bench:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    env:
      BENCHMARKS: tiny,small,medium
      COMPARE_REFS: v0.1.0
    steps:
      - uses: anttikivi/forgejo-status@v0.1.2
        with:
          token: ${{ secrets.CODEBERG_TOKEN }}
          context: ${{ github.workflow }} / ${{ matrix.os }}
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - run: ./zig.ps1 build generate-bench-data -Dbenchmarks="${{ env.BENCHMARKS }}"
      - run: ./zig.ps1 build bench-compare -Dbenchmarks="${{ env.BENCHMARKS }}" -Dcompare-refs="${{ env.COMPARE_REFS }}"
